####################################################
#  Describe File Format .Change Raw File to Pif File
#---------------------------------------------------
# Written by zhung on 2007-01-05
####################################################
package EngineConfig;

@ISA = qw(Exporter);
@EXPORT = qw(engine_config);

use Exporter ();
use strict;

my @rules = (
	{
		'RULE_TYPE' => 'R2P_VV',
		'RULE_NAME' => '',
		'INPUT_FILE_DESCRIPTION' => [".*HOSTPM.*.raw"],
		'FILENAME_FORMAT' => '^(.+)-#-(\w+)-#-(\w+)-#-(\w+)-#-(\w+).raw$',
		'EQUIPID' =>1,
		'BLOCKNAME' => 2,
		'STARTTIME' => 3,
		'ENDTIME' => 4,
		'PERIOD' => 5,
		'LINE_FORMAT' => '^(.+)\:\:(\w+)\.(.+)(\s*)=(\s*)(\w+)(\s*)\:(\s*)(.+)$',
		'MIB_FILENAME' => 1,
		'COUNTER_NAME' => 2,
		'EQUIP_NO' => 3,
		'COUNTER_TYPE' => 6,
		'COUNTER_VALUE' => 9,
		'ORDER_OF_FILES' => 'OLDEST_FIRST',
#		'LINE_COUNTER' => {# 'CPLOAD' => 'laIndex|laNames|laLoad|laConfig|laLoadInt|laLoadFloat|laErrorFlag|laErrMessage',
#			                  #'STORE_DISK' => 'hrStorageIndex|hrStorageType|hrStorageDescr|hrStorageAllocationUnits|hrStorageSize|hrStorageUsed|hrStorageAllocationFailures',
#			                  #'STORE_MEM' => 'hrStorageIndex|hrStorageType|hrStorageDescr|hrStorageAllocationUnits|hrStorageSize|hrStorageUsed|hrStorageAllocationFailures',
#			                  #'PRO_PERF' => 'hrSWRunIndex|hrSWRunName|hrSWRunID|hrSWRunPath|hrSWRunParameters|hrSWRunType|hrSWRunStatus|hrSWRunPerfCPU|hrSWRunPerfMem',
#					              #'PROGRAM' => 'hrSWInstalledID|hrSWInstalledType|hrSWInstalledDate',
#			                  #'PORT_PERF' => 'ifIndex|ifDescr|ifType|ifMtu|ifSpeed|ifPhysAddress|ifAdminStatus|ifOperStatus|ifLastChange|ifInOctets|ifInUcastPkts|ifInNUcastPkts|ifInDiscards|ifInErrors|ifInUnknownProtos|ifOutOctets|ifOutUcastPkts|ifOutNUcastPkts|ifOutDiscards|ifOutErrors|ifOutQLen|ifSpecific',
#			                  #'CPULOAD' => 'hrProcessorFrwID|hrProcessorLoad',
#			                  #'DISKIO' => 'diskIOIndex|diskIODevice|diskIONRead|diskIONWritten|diskIOReads|diskIOWrites',
#			                  #'HOSTDEVICE' => 'hrDeviceIndex|hrDeviceType|hrDeviceDescr|hrDeviceID|hrDeviceStatus',
#			                },
#		#累加指定的数据，如果不使用条件累加则用ALL，否则使用变量；第二部分是表达式中使用的变量名称，方便替换；第三部分是表达式，四则运算
		'ACCU_COLUMN' => {
												'TOTAL_STORE' => 'hrStorageType|hrStorageSize,hrStorageAllocationUnits|hrStorageSize*hrStorageAllocationUnits',
			                	'USED_STORE' => 'hrStorageType|hrStorageUsed,hrStorageAllocationUnits|hrStorageUsed*hrStorageAllocationUnits',
			                	'IN_TRAFFIC' => 'ALL|ifInOctets|ifInOctets',
			                	'OUT_TRAFFIC' => 'ALL|ifOutOctets|ifOutOctets',
			                	'CPLOAD' => 'laIndex|laLoadInt|laLoadInt',
												'INDISCARDSALL' => 'All|ifInDiscards|ifInDiscards',
												'OUTDISCARDSALL' => 'All|ifOutDiscards|ifOutDiscards',
												'INUCASTPKTSALL' => 'ALL|ifInUcastPkts|ifInUcastPkts',
												'OUTUCASTPKTSALL' => 'All|ifOutUcastPkts|ifOutUcastPkts',
												'INNUCASTPKTSALL' => 'All|InNUcastPkts|InNUcastPkts',
												'OUTNUCASTPKTSALL' => 'All|OutNUcastPkts|OutNUcastPkts',
												'SPEED' => 'All|ifSpeed|ifSpeed',
												'CPUNO' => 'hrDeviceType|hrDeviceIndex|hrDeviceIndex/hrDeviceIndex',
			               },
		#存放上一次采集的数据，供累加型数据做基数用
		'HIS_DATA_DIR' => '/ioss/pm/parser/config',
		'OIDNAME_FILE' => '/ioss/pm/parser/OID2NAME/DISKIO',
		'REPLACE_RULE' => '^(.+)\.(.+)(\s*)=(.+)$',
	},
	{
		'RULE_TYPE' => 'R2P_VV',
		'RULE_NAME' => '',
		'INPUT_FILE_DESCRIPTION' => [".*DDOS.*.raw"],
		'FILENAME_FORMAT' => '^(.+)-#-(\w+)-#-(\w+)-#-(\w+)-#-(\w+).raw$',
		'EQUIPID' =>1,
		'BLOCKNAME' => 2,
		'STARTTIME' => 3,
		'ENDTIME' => 4,
		'PERIOD' => 5,
		'LINE_FORMAT' => '^(.+)\:\:(\w+)\.(.+)(\s*)=(\s*)(\w+)(\s*)\:(\s*)(.+)$',
		'MIB_FILENAME' => 1,
		'COUNTER_NAME' => 2,
		'EQUIP_NO' => 3,
		'COUNTER_TYPE' => 6,
		'COUNTER_VALUE' => 9,
		'ORDER_OF_FILES' => 'OLDEST_FIRST',
		#累加指定的数据，如果不使用条件累加则用ALL，否则使用变量；第二部分是表达式中使用的变量名称，方便替换；第三部分是表达式，四则运算
		'ACCU_COLUMN' => {
			                	'IN_TRAFFIC' => 'ALL|ifInOctets|ifInOctets',
			                	'OUT_TRAFFIC' => 'ALL|ifOutOctets|ifOutOctets',
			               },
		#存放上一次采集的数据，供累加型数据做基数用
		'HIS_DATA_DIR' => '/ioss/pm/parser/config',
		'OIDNAME_FILE' => '/ioss/pm/parser/OID2NAME/DISKIO',
		'REPLACE_RULE' => '^(.+)\.(.+)(\s*)=(.+)$',
	},
	{
		'RULE_TYPE' => 'R2P_VV',
		'RULE_NAME' => '',
		'INPUT_FILE_DESCRIPTION' => [".*IPS.*.raw"],
		'FILENAME_FORMAT' => '^(.+)-#-(\w+)-#-(\w+)-#-(\w+)-#-(\w+).raw$',
		'EQUIPID' =>1,
		'BLOCKNAME' => 2,
		'STARTTIME' => 3,
		'ENDTIME' => 4,
		'PERIOD' => 5,
		'LINE_FORMAT' => '^(.+)\:\:(\w+)\.(.+)(\s*)=(\s*)(\w+)(\s*)\:(\s*)(.+)$',
		'MIB_FILENAME' => 1,
		'COUNTER_NAME' => 2,
		'EQUIP_NO' => 3,
		'COUNTER_TYPE' => 6,
		'COUNTER_VALUE' => 9,
		'ORDER_OF_FILES' => 'OLDEST_FIRST',
		'ACCU_COLUMN' => {
			                	'INTRAFFIC' => 'ALL|ifinoctets|ifinoctets',
			                	'OUTTRAFFIC' => 'ALL|ifoutoctets|ifoutoctets',
											  'PORTTOT' => 'ALL|ifindex|ifindex/ifindex',
			               },
		#存放上一次采集的数据，供累加型数据做基数用
		'HIS_DATA_DIR' => '/ioss/pm/parser/config',
		'OIDNAME_FILE' => '/ioss/pm/parser/OID2NAME/IPS',
		'REPLACE_RULE' => '^(.+)\.(.+)(\s*)=(.+)$',
	},
	{
		'RULE_TYPE' => 'R2P_VV',
		'RULE_NAME' => '',
		'INPUT_FILE_DESCRIPTION' => [".*AUDIT.*.raw"],
		'FILENAME_FORMAT' => '^(.+)-#-(\w+)-#-(\w+)-#-(\w+)-#-(\w+).raw$',
		'EQUIPID' =>1,
		'BLOCKNAME' => 2,
		'STARTTIME' => 3,
		'ENDTIME' => 4,
		'PERIOD' => 5,
		'LINE_FORMAT' => '^(.+)\:\:(\w+)\.(.+)(\s*)=(\s*)(\w+)(\s*)\:(\s*)(.+)$',
		'MIB_FILENAME' => 1,
		'COUNTER_NAME' => 2,
		'EQUIP_NO' => 3,
		'COUNTER_TYPE' => 6,
		'COUNTER_VALUE' => 9,
		'ORDER_OF_FILES' => 'OLDEST_FIRST',
		'ACCU_COLUMN' => {
					'TOTAL_STORE' => 'hrStorageType|hrStorageSize,hrStorageAllocationUnits|hrStorageSize*hrStorageAllocationUnits',
			    'USED_STORE' => 'hrStorageType|hrStorageUsed,hrStorageAllocationUnits|hrStorageUsed*hrStorageAllocationUnits',
			    'IN_TRAFFIC' => 'ALL|ifInOctets|ifInOctets',
			    'OUT_TRAFFIC' => 'ALL|ifOutOctets|ifOutOctets',
					'INDISCARDSALL' => 'All|ifInDiscards|ifInDiscards',
					'OUTDISCARDSALL' => 'All|ifOutDiscards|ifOutDiscards',
					'INUCASTPKTSALL' => 'ALL|ifInUcastPkts|ifInUcastPkts',
					'OUTUCASTPKTSALL' => 'All|ifOutUcastPkts|ifOutUcastPkts',
					'INNUCASTPKTSALL' => 'All|InNUcastPkts|InNUcastPkts',
					'OUTNUCASTPKTSALL' => 'All|OutNUcastPkts|OutNUcastPkts',
					'SPEED' => 'All|ifSpeed|ifSpeed',
		},
		'HIS_DATA_DIR' => '/ioss/pm/parser/config',
		'OIDNAME_FILE' => '/ioss/pm/parser/OID2NAME/DISKIO',
    'REPLACE_RULE' => '^(.+)\.(.+)(\s*)=(.+)$',
	},
	{
		'RULE_TYPE' => 'R2P_VV',
		'RULE_NAME' => '',
		'INPUT_FILE_DESCRIPTION' => [".*VPN.*.raw"],
		'FILENAME_FORMAT' => '^(.+)-#-(\w+)-#-(\w+)-#-(\w+)-#-(\w+).raw$',
		'EQUIPID' =>1,
		'BLOCKNAME' => 2,
		'STARTTIME' => 3,
		'ENDTIME' => 4,
		'PERIOD' => 5,
		'LINE_FORMAT' => '^(.+)\:\:(\w+)\.(.+)(\s*)=(\s*)(\w+)(\s*)\:(\s*)(.+)$',
		'MIB_FILENAME' => 1,
		'COUNTER_NAME' => 2,
		'EQUIP_NO' => 3,
		'COUNTER_TYPE' => 6,
		'COUNTER_VALUE' => 9,
		'ORDER_OF_FILES' => 'OLDEST_FIRST',
		#累加指定的数据，如果不使用条件累加则用ALL，否则使用变量；第二部分是表达式中使用的变量名称，方便替换；第三部分是表达式，四则运算
		'ACCU_COLUMN' => {
			                	'IN_TRAFFIC' => 'ALL|ifInOctets|ifInOctets',
			                	'OUT_TRAFFIC' => 'ALL|ifOutOctets|ifOutOctets',
						'INDISCARDSALL' => 'All|ifInDiscards|ifInDiscards',
						'OUTDISCARDSALL' => 'All|ifOutDiscards|ifOutDiscards',
						'INUCASTPKTSALL' => 'ALL|ifInUcastPkts|ifInUcastPkts',
						'OUTUCASTPKTSALL' => 'All|ifOutUcastPkts|ifOutUcastPkts',
						'INNUCASTPKTSALL' => 'All|InNUcastPkts|InNUcastPkts',
						'OUTNUCASTPKTSALL' => 'All|OutNUcastPkts|OutNUcastPkts',
						'SPEED' => 'All|ifSpeed|ifSpeed',
			               },
		#存放上一次采集的数据，供累加型数据做基数用
		'HIS_DATA_DIR' => '/ioss/pm/parser/config',
		'OIDNAME_FILE' => '/ioss/pm/parser/OID2NAME/DISKIO',
		'REPLACE_RULE' => '^(.+)\.(.+)(\s*)=(.+)$',
	},
	
	{
		'RULE_TYPE' => 'R2P_VV',
		'RULE_NAME' => '',
		'INPUT_FILE_DESCRIPTION' => [".*ROUTER.*.raw"],
		'FILENAME_FORMAT' => '^(.+)-#-(\w+)-#-(\w+)-#-(\w+)-#-(\w+).raw$',
		'EQUIPID' =>1,
		'BLOCKNAME' => 2,
		'STARTTIME' => 3,
		'ENDTIME' => 4,
		'PERIOD' => 5,
		'LINE_FORMAT' => '^(.+)\:\:(\w+)\.(.+)(\s*)=(\s*)(\w+)(\s*)\:(\s*)(.+)$',
		'MIB_FILENAME' => 1,
		'COUNTER_NAME' => 2,
		'EQUIP_NO' => 3,
		'COUNTER_TYPE' => 6,
		'COUNTER_VALUE' => 9,
		'ORDER_OF_FILES' => 'OLDEST_FIRST',
		'LINE_COUNTER' => { 'ROUTERPORT' => 'ifIndex|ifDescr|ifType|ifMtu|ifSpeed|ifPhysAddress|ifAdminStatus|ifOperStatus|ifLastChange|ifInOctets|ifInUcastPkts|ifInNUcastPkts|ifInDiscards|ifInErrors|ifInUnknownProtos|ifOutOctets|ifOutUcastPkts|ifOutNUcastPkts|ifOutDiscards|ifOutErrors|ifOutQLen|ifSpecific',
		#	            			'ROUTERVLAN' => 'ifIndex|ifDescr|ifType|ifMtu|ifSpeed|ifPhysAddress|ifAdminStatus|ifOperStatus|ifLastChange|ifInOctets|ifInUcastPkts|ifInNUcastPkts|ifInDiscards|ifInErrors|ifInUnknownProtos|ifOutOctets|ifOutUcastPkts|ifOutNUcastPkts|ifOutDiscards|ifOutErrors|ifOutQLen|ifSpecific',
		},
		'ACCU_COLUMN' => {
			                'IN_TRAFFIC' => 'ALL|ifInOctets|ifInOctets',
			                'OUT_TRAFFIC' => 'ALL|ifOutOctets|ifOutOctets',
			               #'CPLOAD' => 'laIndex|laLoadInt|laLoadInt',
					'INDISCARDSALL' => 'All|ifInDiscards|ifInDiscards',
					'OUTDISCARDSALL' => 'All|ifOutDiscards|ifOutDiscards',
					'INUCASTPKTSALL' => 'ALL|ifInUcastPkts|ifInUcastPkts',
					'OUTUCASTPKTSALL' => 'All|ifOutUcastPkts|ifOutUcastPkts',
					'INNUCASTPKTSALL' => 'All|InNUcastPkts|InNUcastPkts',
					'OUTNUCASTPKTSALL' => 'All|OutNUcastPkts|OutNUcastPkts',
					'MEMUSED' => 'All|cempMemPoolUsed|cempMemPoolUsed',
					'MEMFREE' => 'All|cempMemPoolFree|cempMemPoolFree',
					'PORTAVA' => 'All|ifAdminStatus|ifAdminStatus',
					'PORTUSED' => 'ifAdminStatus|ifIndex|ifIndex/ifIndex',	
		},
		#存放上一次采集的数据，供累加型数据做基数用
		'HIS_DATA_DIR' => '/ioss/pm/parser/config',
		'OIDNAME_FILE' => '/ioss/pm/parser/OID2NAME/ROUTER',
		'REPLACE_RULE' => '^(.+)\.(.+)(\s*)=(.+)$',
		
	},

#	{
#  	'RULE_TYPE' => 'R2P_VV',
#  	'RULE_NAME' => '',
#  	'INPUT_FILE_DESCRIPTION' => [".*HSTORE.*.raw"],
#  	'FILENAME_FORMAT' => '^(.+)-#-(\w+)-#-(\w+)-#-(\w+)-#-(\w+).raw$',
#  	'EQUIPID' =>1,
#  	'BLOCKNAME' => 2,
#  	'STARTTIME' => 3,
#  	'ENDTIME' => 4,
#  	'PERIOD' => 5,
#  	'LINE_FORMAT' => '^(.+)\:\:(\w+)\.(.+)(\s*)=(\s*)(\w+)(\s*)\:(\s*)(.+)$',
#  	'MIB_FILENAME' => 1,
#  	'COUNTER_NAME' => 2,
#  	'EQUIP_NO' => 3,
#  	'COUNTER_TYPE' => 6,
#  	'COUNTER_VALUE' => 9,
#  	'ORDER_OF_FILES' => 'OLDEST_FIRST',
#  	'LINE_COUNTER' => { 
#  											'COMMON' => 'deviceId|status|totalCapacity|usedCapacity',
#  											'PERF' => 'hwPerfPortIfIndex|hwPerfNodeCPUUsage|hwPerfNodeMemoryUsage|hwPerfNodeDelay|hwPerfNodeTotalIOPS|hwPerfNodeReadIOPS|hwPerfNodeWriteIOPS|hwPerfNodeTotalTraffic|hwPerfNodeReadTraffic|hwPerfNodeWriteTraffic|hwPerfLunHitRate|hwPerfLunTotalIOPS|hwPerfLunReadIOPS|hwPerfLunWriteIOPS|hwPerfLunTotalTraffic|hwPerfLunReadTraffic|hwPerfLunWriteTraffic|hwPerfLunReadIORate|hwPerfLunWriteIORate|hwPerfLunMaxTraffic|hwPerfLunMaxIOPS|hwPerfPortDelay|hwPerfPortTotalIOPS|hwPerfPortReadIOPS|hwPerfPortWriteIOPS|hwPerfPortTotalTraffic|hwPerfPortReadTraffic|hwPerfPortWriteTraffic|hwPerfPortMaxTraffic|hwPerfPortMaxIOPS|hwPerfCacheReadUtilization|hwPerfCacheWriteUtilization|hwPerfCacheHitRatio',
#  											'STORE_LOGIC' => 'hwStorageControllerID|hwStorageControllerTemperature|hwStorageCacheID|hwStorageCacheTotalCapacity|hwStorageLunID|hwStorageLunCapacity|hwStorageNodeIfIndex|hwStorageNodeStatus|hwStorageControllerName|hwStorageControllerHealthStatus|hwStorageControllerRunningStatus|hwStorageControllerSoftVer|hwStorageControllerMemorySize|hwStorageControllerCPUInfo|hwStorageControllerVoltage|hwStorageLunName|hwStorageLunOwningRaid|hwStorageLunOwningController|hwStorageLunStatus|hwStorageLunRowStatus|hwStorageCacheRowStatus',
#  											'STORE_MIB' => 'hwInfoControllerID|hwInfoControllerCpuUsingRatio|hwInfoControllerMemoryUsingRatio|hwInfoControllerStatus|hwInfoRAIDID|hwInfoRAIDName|hwInfoRAIDLevel|hwInfoRAIDFreeCapacity|hwInfoRAIDStatus|hwInfoRAIDTotalSize|hwInfoCacheID|hwInfoCacheTotalMemoryCapacity|hwInfoCacheSystemMemoryCapacity|hwInfoCacheCacheCapacity|hwInfoCacheCacheUtilization|hwInfoCacheCacheHitRatio|hwInfoCacheReadCacheUtility|hwInfoCacheWriteCacheUtililty',
#  											
#  	},
#  	'HIS_DATA_DIR' => '/home/nuoen/back/pm/parser/config',
#  	'OIDNAME_FILE' => '/home/nuoen/back/pm/parser/OID2NAME/STORE',
#     'REPLACE_RULE' => '^(.+)\.(.+)(\s*)=(.+)$',		
#  }, 

	{
		'RULE_TYPE' => 'R2P_VV',
		'RULE_NAME' => '',
		'INPUT_FILE_DESCRIPTION' => [".*SWITCH.*.raw"],
		'FILENAME_FORMAT' => '^(.+)-#-(\w+)-#-(\w+)-#-(\w+)-#-(\w+).raw$',
		'EQUIPID' =>1,
		'BLOCKNAME' => 2,
		'STARTTIME' => 3,
		'ENDTIME' => 4,
		'PERIOD' => 5,
		'LINE_FORMAT' => '^(.+)\:\:(\w+)\.(.+)(\s*)=(\s*)(\w+)(\s*)\:(\s*)(.+)$',
		'MIB_FILENAME' => 1,
		'COUNTER_NAME' => 2,
		'EQUIP_NO' => 3,
		'COUNTER_TYPE' => 6,
		'COUNTER_VALUE' => 9,
		'ORDER_OF_FILES' => 'OLDEST_FIRST',
		'LINE_COUNTER' => { 
		#	            			'SWITCHVLAN' => 'ifIndex|ifDescr|ifType|ifMtu|ifSpeed|ifPhysAddress|ifAdminStatus|ifOperStatus|ifLastChange|ifInOctets|ifInUcastPkts|ifInNUcastPkts|ifInDiscards|ifInErrors|ifInUnknownProtos|ifOutOctets|ifOutUcastPkts|ifOutNUcastPkts|ifOutDiscards|ifOutErrors|ifOutQLen|ifSpecific',
			            			'SWITCHPORT' => 'ifIndex|ifDescr|ifType|ifMtu|ifSpeed|ifPhysAddress|ifAdminStatus|ifOperStatus|ifLastChange|ifInOctets|ifInUcastPkts|ifInNUcastPkts|ifInDiscards|ifInErrors|ifInUnknownProtos|ifOutOctets|ifOutUcastPkts|ifOutNUcastPkts|ifOutDiscards|ifOutErrors|ifOutQLen|ifSpecific',
		},
		'ACCU_COLUMN' => {
			'IN_TRAFFIC' => 'ALL|ifInOctets|ifInOctets',
          		'OUT_TRAFFIC' => 'ALL|ifOutOctets|ifOutOctets',
			'CPLOAD' => 'All|hh3cEntityExtCpuUsage|hh3cEntityExtCpuUsage',
			'MEMSIZE' => 'All|hh3cEntityExtMemSize|hh3cEntityExtMemSize',
			'MEMUSAGE' => 'All|hh3cEntityExtMemUsage|hh3cEntityExtMemUsage',
			'INDISCARDSALL' => 'All|ifInDiscards|ifInDiscards',
                        'OUTDISCARDSALL' => 'All|ifOutDiscards|ifOutDiscards',
                        'INUCASTPKTSALL' => 'ALL|ifInUcastPkts|ifInUcastPkts',
                        'OUTUCASTPKTSALL' => 'All|ifOutUcastPkts|ifOutUcastPkts',
                        'INNUCASTPKTSALL' => 'All|InNUcastPkts|InNUcastPkts',
                        'OUTNUCASTPKTSALL' => 'All|OutNUcastPkts|OutNUcastPkts',
			'PORTAVA' => 'All|ifAdminStatus|ifAdminStatus',
			'PORTUSED' => 'ifAdminStatus|ifIndex|ifIndex/ifIndex',	
		},
		'HIS_DATA_DIR' => '/ioss/pm/parser/config',
    		'OIDNAME_FILE' => '/ioss/pm/parser/OID2NAME/SWITCH',
    		'REPLACE_RULE' => '^(.+)\.(.+)(\s*)=(.+)$',
	},
	{
		'RULE_TYPE' => 'R2P_VV',
		'RULE_NAME' => '',
		'INPUT_FILE_DESCRIPTION' => [".*FW.*.raw"],
		'FILENAME_FORMAT' => '^(.+)-#-(\w+)-#-(\w+)-#-(\w+)-#-(\w+).raw$',
		'EQUIPID' =>1,
		'BLOCKNAME' => 2,
		'STARTTIME' => 3,
		'ENDTIME' => 4,
		'PERIOD' => 5,
		'LINE_FORMAT' => '^(.+)\:\:(\w+)\.(.+)(\s*)=(\s*)(\w+)(\s*)\:(\s*)(.+)$',
		'MIB_FILENAME' => 1,
		'COUNTER_NAME' => 2,
		'EQUIP_NO' => 3,
		'COUNTER_TYPE' => 6,
		'COUNTER_VALUE' => 9,
		'ORDER_OF_FILES' => 'OLDEST_FIRST',
		'ACCU_COLUMN' => {
					'IN_TRAFFIC' => 'ALL|ifInOctets|ifInOctets',
					'OUT_TRAFFIC' => 'ALL|ifOutOctets|ifOutOctets',
					'INDISCARDSALL' => 'All|ifInDiscards|ifInDiscards',
					'OUTDISCARDSALL' => 'All|ifOutDiscards|ifOutDiscards',
					'INUCASTPKTSALL' => 'ALL|ifInUcastPkts|ifInUcastPkts',
					'OUTUCASTPKTSALL' => 'All|ifOutUcastPkts|ifOutUcastPkts',
					'INNUCASTPKTSALL' => 'All|InNUcastPkts|InNUcastPkts',
					'OUTNUCASTPKTSALL' => 'All|OutNUcastPkts|OutNUcastPkts',                             
					#'TOTAL_STORE' => 'hrStorageType|hrStorageSize,hrStorageAllocationUnits|hrStorageSize*hrStorageAllocationUnits',
					#'USED_STORE' => 'hrStorageType|hrStorageUsed,hrStorageAllocationUnits|hrStorageUsed*hrStorageAllocationUnits',
		},
		'HIS_DATA_DIR' => '/ioss/pm/parser/config',
    'OIDNAME_FILE' => '/ioss/pm/parser/OID2NAME/DP',
    'REPLACE_RULE' => '^(.+)(\s*)=(.+)$',
	},
	{
		'RULE_TYPE' => 'R2P_VV',
		'RULE_NAME' => '',
		'INPUT_FILE_DESCRIPTION' => [".*MYSQL.*.raw"],
		'FILENAME_FORMAT' => '^(.+)-#-(\w+)-#-(\w+)-#-(\w+)-#-(\w+).raw$',
		'EQUIPID' =>1,
		'BLOCKNAME' => 2,
		'STARTTIME' => 3,
		'ENDTIME' => 4,
		'PERIOD' => 5,
		'LINE_FORMAT' => '^(.+)\:\:(\w+)\.(.+)(\s*)=(\s*)(\w+)(\s*)\:(\s*)(.*)$',
		'MIB_FILENAME' => 1,
		'COUNTER_NAME' => 2,
		'EQUIP_NO' => 3,
		'COUNTER_TYPE' => 6,
		'COUNTER_VALUE' => 9,
		'ORDER_OF_FILES' => 'OLDEST_FIRST',
		'HIS_DATA_DIR' => '/ioss/pm/parser/config',
	},
	{
		'RULE_TYPE' => 'R2P_VV',
		'RULE_NAME' => '',
		'INPUT_FILE_DESCRIPTION' => [".*LB.*.raw"],
		'FILENAME_FORMAT' => '^(.+)-#-(\w+)-#-(\w+)-#-(\w+)-#-(\w+).raw$',
		'EQUIPID' =>1,
		'BLOCKNAME' => 2,
		'STARTTIME' => 3,
		'ENDTIME' => 4,
		'PERIOD' => 5,
		'LINE_FORMAT' => '^(.+)\:\:(\w+)\.(.+)(\s*)=(\s*)(\w+)(\s*)\:(\s*)(.+)$',
		'MIB_FILENAME' => 1,
		'COUNTER_NAME' => 2,
		'EQUIP_NO' => 3,
		'COUNTER_TYPE' => 6,
		'COUNTER_VALUE' => 9,
		'ORDER_OF_FILES' => 'OLDEST_FIRST',
		'HIS_DATA_DIR' => '/ioss/pm/parser/config',
    'OIDNAME_FILE' => '/ioss/pm/parser/OID2NAME/DP',
    'REPLACE_RULE' => '^(.+)\.(.+)(\s*)=(.+)$',
	},
#	{
#		'RULE_TYPE' => 'R2P_SDR',
#		'RULE_NAME' => '',
#		'INPUT_FILE_DESCRIPTION' => [".*SENSORPM.*.raw"],
#		'FILENAME_FORMAT' => '^(.+)-#-(\w+)-#-(\w+)-#-(\w+)-#-(\w+)-#-(\w+).raw$',
#		'CUSTOMID' => 1,
#		'EQUIPID' => 2,
#		'BLOCKNAME' => 3,
#		'STARTTIME' => 4,
#		'ENDTIME' => 5,
#		'PERIOD' => 6,
#		'LINE_FORMAT' => '^(.*)\|(.*)\|(.*)$',
#		'SDRNAME' => 1,
#		'SDRVALUE' => 2,
#		'SDRTYPE' => 3,
#	},
	#能力引擎话单解析配置	
#	{
#		'RULE_TYPE' => 'R2P_ENG',
#		'RULE_NAME' => '',
#		'INPUT_FILE_DESCRIPTION' => [".*detail.*.req"],
#		'FILENAME_FORMAT' => '^(\w+)\_(\d+)\_(\d+)\_(\d+)\_(\d+)\_(\d+).req$',
#		'SERVICEID' => 3,
#		'PROVID' => 5,
#		'BLOCKNAME' => 'ENGINE',
#		'HEADCOLS'=>'FILESEQ|FILEVER|CREATETIME|CREATESYSID|ACCEPTSYSID|WSTARTTIME|WENDTIME|TOTAL|REMARK|PROVID|SERVICEID',
#		'BODYCOLS'=>'SEQNUM|TIME|MESSAGEID|SPID|SERVICEID|CPID|CONTENTID|ACCESSNO|SERVICETYPE|SOURCEDEVICE_TYPE|SOURCEDEVICE_ID|CDRTYPE|PRODUCTID|SPC_PRODUCTID|SP_PRODUCTID|ORDERMETHOD|PUSHID|OAMDN|DAMDN|FAMDN|USERTYPE|STARTTIME|ENDTIME|TIMESEC|INPUTOCTETS|OUTPUTOCTETS|FEEPOINT|BILLINGTYPE|FEE|SYSCODE1|SYSCODE2',
#	},
	#统一资源话单解析配置
#	{
#		'RULE_TYPE' => 'R2P_UNIRNESS',
#		'RULE_NAME' => '',
#		'INPUT_FILE_DESCRIPTION' => [".*host.*.json",
#		                             ".*storage.*.json",
#		                             ".*snapshots.*.json",
#		                             ".*query.*.json",
#		                             ".*database.*.json",
#		                             ".*dbinstance.*.json",
#		                             ".*baklist.*.json",
#		                             ".*user.*.json",
#		                             ".*vmlist_.*.json"
#		                             ],
#		'FILENAME_FORMAT' => '^(\w+)\_(\w+)\_(\d+).json$',
#		'SYSNAME' => 1,
#		'NENAME' => 2,
#		'FILE_FORM' => {'host_head' => 'message|totalCount|pageIndex|pageSize|startIndex|result',
#										'host_body' => 'mgmtEntityId|mgmtEntityName|ipAddress|parentId|cpunum|memorysize|pdcId|partyId|osinfo|username|password|mhostId|clusterId',
#										'storage_head' => 'message|totalCount|pageIndex|pageSize|startIndex|result',
#										'storage_body' => 'mgmtEntityId|mgmtEntityName|parentId|pdcId|partyId|vmName',
#										'snapshots_head' => 'message|totalCount|pageIndex|pageSize|startIndex|result',
#										'snapshots_body' => 'mgmtEntityId|mgmtEntityName|parentId|description',
#										'query_head' => 'message|totalCount|pageIndex|pageSize|startIndex|result',
#										'query_body' => 'mgmtEntityId|mgmtEntityName|ipAddress|parentId|vlanId|mac|pdcId|isBand|partyId',
#										'database_head' => 'message|totalCount|pageIndex|pageSize|startIndex|result',
#										'database_body' => 'mgmtEntityId|mgmtEntityName|parentId|db_type|db_template|available|dbhost|dbport|database_name|instancesize|partyId',
#										'dbinstance_head' =>  'message|totalCount|pageIndex|pageSize|startIndex|result',
#										'dbinstance_body' => 'mgmtEntityId|mgmtEntityName|parentId|available|name|host|port|type|installPath',
#										'baklist_head' => 'message|totalCount|pageIndex|pageSize|startIndex|result',
#										'baklist_body' => 'mgmtEntityId|mgmtEntityName|parentId',
#										'user_head' => 'message|totalCount|pageIndex|pageSize|startIndex|result',
#										'user_body' => 'mgmtEntityId|mgmtEntityName|parentId|daas_username|daas_password',
#										'vmlist_head' => 'message|result|totalCount|pageIndex|pageSize|startIndex',
#										'vmlist_body'=>'mgmtEntityId|mgmtEntityName|ipAddress|vmType|cpunum|memorysize|disksize|repositoryId|osinfo|hostId|partyId'
#									},
#	},
#	#性能监控和统一计量话单解析配置
#	{
#			'RULE_TYPE' => 'R2P_MOME',
#			'RULE_NAME' => '',
#			'INPUT_FILE_DESCRIPTION' => [
#					                         ".*obj.*.json"
#		    	                        ],
#			'FILENAME_FORMAT' => '^(\w+)\_(\w+)\_(\w+)\_(\d+)_(\w+).json$',
#			'SYSNAME' => 1,
#			'NENAME' => 3,
#			'FILE_FORM' => {'obj_head'=>'ip|type|id',
#											'obj_body'=>'unit|value|key|time'
#										 },
#	},
	#Tomcat性能数据解析配置
	{
		'RULE_TYPE' => 'P2R_TOMCAT',
		'RULE_NAME' => '',
		'INPUT_FILE_DESCRIPTION' => [".*TOMCAT-.*.raw"],
		'FILENAME_FORMAT' => '^(.+)-#-(\w+)-#-(\w+)-#-(\w+)-#-(\w+).raw$',
		'EQUIPID' =>1,
		'BLOCKNAME' => 2,
		'STARTTIME' => 3,
		'ENDTIME' => 4,
		'PERIOD' => 5,
	},
	{
		'RULE_TYPE' => 'R2P_VV',
		'RULE_NAME' => '',
		'INPUT_FILE_DESCRIPTION' => [".*TOMCAT_SNMP.*.raw"],
		'FILENAME_FORMAT' => '^(.+)-#-(.+)-#-(\w+)-#-(\w+)-#-(\w+).raw$',
		'EQUIPID' =>1,
		'BLOCKNAME' => 2,
		'STARTTIME' => 3,
		'ENDTIME' => 4,
		'PERIOD' => 5,
		'LINE_FORMAT' => '^(.+)\:\:(\w+)\.(.+)(\s*)=(\s*)(\w+)(\s*)\:(\s*)(\w+)$',
		'MIB_FILENAME' => 1,
		'COUNTER_NAME' => 2,
		'EQUIP_NO' => 3,
		'COUNTER_TYPE' => 6,
		'COUNTER_VALUE' => 9,
		'ORDER_OF_FILES' => 'OLDEST_FIRST',
		'LINE_COUNTER' => { 	'TOMCATWEB' => 'Wmname|WMencodedPath|WMcacheTTL|WMstartTime|WMservlets|WMprocessingTime|WMcacheObjectMaxSize|WMunloadDelay|WMminTime|WMtldScanTime|WMchildren|WMerrorCount|WMmaxTime|WMstartupTime|WMwelcomeFiles|WMrequestCount|WMsessionTimeout|WMcacheMaxSize|WMdisplayName',
													'TOMCATTP' => 'TPcurrentThreadCount|TPmaxThreads|TPacceptorThreadPriority|TPminSpareThreads|TPlocalPort|TPconnectionCount|TPrunning|TPname|TPmaxHeaderCount|TPmaxConnections|TPsoTimeout|TPcurrentThreadsBusy',
													'TOMCATSERVLET' => 'ServletclassLoadTime|ServleterrorCount|ServletloadTime|ServletprocessingTime|ServletrequestCount|ServletstateManageable|ServletName|Servletwebmodule',
													'TOMCATJSP' => 'JspMonjspCount|JspMonjspReloadCount|JspMonjspUnloadCount|JspMonjspQueueLength|JspMonWebmodule',
													'TOMCATGRP' => 'GRPName|GRPbytesSent|GRPbytesReceived|GRPerrorCount|GRPprocessingTime|GRPrequestCount|GRPmaxTime',
				#									'TOMCATCACHE' => 'SCaccessCount|SCcacheSize|SCaccessCount',
		},
		'HIS_DATA_DIR' => '/ioss/pm/parser/config',
	},
);


sub engine_config{
	return \@rules;
}

1;
